package com.example.trailblitz;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

import com.example.trailblitz.db.AppDatabase;

@Entity(tableName = AppDatabase.PURCHASE_TABLE)
public class Purchase {
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "mTransaction")
    private int mTransaction;

    public int getTransaction() {
        return mTransaction;
    }

    public void setTransaction(int transaction) {
        this.mTransaction = transaction;
    }

    @ColumnInfo(name = "mUserId")
    private int mUserId;    // not autogenerated

    @ColumnInfo(name = "mItemName")
    private String mItemName;

    @ColumnInfo(name = "mItemPrice")
    private double mItemPrice;
    @ColumnInfo(name = "mQuantity")
    private int mQuantity;

    @ColumnInfo(name = "mHasPurchased")
    private boolean mHasPurchased;

    public Purchase(int mUserId, String mItemName, double mItemPrice, int mQuantity, boolean mHasPurchased) {
        this.mUserId = mUserId;
        this.mItemName = mItemName;
        this.mItemPrice = mItemPrice;
        this.mQuantity = mQuantity;
        this.mHasPurchased = mHasPurchased;
    }

    public int getUserId() {
        return mUserId;
    }

    public void setUserId(int userId) {
        this.mUserId = userId;
    }

    public String getItemName() {
        return mItemName;
    }

    public void setItemName(String itemName) {
        this.mItemName = itemName;
    }

    public double getItemPrice() {
        return mItemPrice;
    }

    public void setItemPrice(double itemPrice) {
        this.mItemPrice = itemPrice;
    }

    public int getQuantity() {
        return mQuantity;
    }

    public void setQuantity(int quantity) {
        this.mQuantity = quantity;
    }

    public boolean getHasPurchased() {
        return mHasPurchased;
    }

    public void setHasPurchased(boolean hasPurchased) {
        this.mHasPurchased = hasPurchased;
    }
}
